config/routes.rb
#encoding: utf-8
Weber::Application.routes.draw do

  get "session/create"
  
  get "/intro" => "home#index", :as => "intro"

  resources :submits, :feedbacks, :assignments, :comments, :courses
  
  resources :notifications do
    delete :clear, :on => :collection
    get :read, :on => :member
  end

  # 管理员
  namespace :admin do
    resources :courses do
	    get "/download_courseware" => "courses#download_courseware", :as => :download
      # admin course-poster  
      post 'update_poster' => 'courses#update_poster', :as => :update_poster
      # admin course-courseware
      match 'edit_courseware' => 'courses#edit_courseware'
    end
  end

  #邮箱激活
  get '/users(:cad_id,:activate_code)' => 'users#activate_account'
  # 成功页面
  match 'success' => "users#success", :as => :success
  match 'failure' => "users#failure", :as => :failure
	# 编辑edit操作路由
	match '/sign_in' => "sessions#new", :via => :get, :as => :new_session
  match "logout" => "sessions#logout", :as => "logout"
  match '/sign_up' => "users#new", :as => :new_user
	get ':member_name/edit' => 'users#edit', :as => :user_edit
	post '/:member_name/show' => "users#update"
	get '/:member_name' => 'users#show', :as => :user_show
  match '/sessions_path' => "sessions#create", :as => "sessions", :via => :post
  
  get "/:member_name" => "home#show", :as => "member"
  post "/member" => "users#create"

	match "/update_avatar/:member_name" => "users#update_avatar",:as => :update_avatar 
  

  # 课程异步加载
  get "/courses/:course_id/comments" => "comments#index", :as => "comments"
  #get "assignments" => "courses#show", :as => "assignment"

  root :to => 'home#show'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :commentable_id, :commentable_type, :user_id

  validates :content, :commentable_id, :commentable_type, :user_id, :presence => true

  belongs_to :user

  #counter_cacha在commentable中有一个comments_count字段
  belongs_to :commentable, :polymorphic => true, :counter_cache => true
  
  after_create :send_notifications
  
  def mentioned_users
    mentioned_names = self.content.scan(Notifiable::MENTION_REGEXP).collect {|matched| matched.first}.uniq
    #发表评的人
    mentioned_names.delete(self.user.name)
    #课程发起人
    mentioned_names.delete(self.commentable.user.name)
    mentioned_names.map { |name| User.find_by_name(name) }.compact
  end


  private

    def send_notifications
      # send notification to commentable owner
      # unless the comment was created by the same owner
      # send to commentable's author
      send_notification_to(
        self.commentable.user,
        Notification::ACTION_REPLY) unless self.user == self.commentable.user
      send_notification_to_mentioned_users
    end

    def send_notification_to(user, action)
      Notification.notify(
        user,
        self.commentable,
        self.user,
        action,
        self.content
      )
    end

    def send_notification_to_mentioned_users
      mentioned_users.each do |user|
        send_notification_to(user, Notification::ACTION_MENTION)
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :find_commentable, :only => [:create]
 
  def index
    course = Course.find(params[:course_id])
    @course_id = course.id
    @comment = Comment.new
    @comments = course.comments

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @commentable.comments.build(params[:comment])
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.js { render 'add_comment' }
      else
        # to-do
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.comment
  .avatar
    = image_tag "#{comment.user.avatar_url}", :size => "64x64"
  .main
    .headline
      .name #{comment.user.name}
      .reply
        =image_tag("/assets/reply_button.png", :class => "mention_button", data: { mention: "@#{ comment.user.name }" }) 
    -if comment.user.is_admin?
      .comment_content.content-role.admin-comment-content #{markdown(comment.content)}
    -else
      .comment_content.content-role #{markdown(comment.content)}
    .clear

app/views/comments/_form.html.erb
<% if current_user %>
<div class="comment" id="new_comment">
      <div class="avatar"><img alt="Avatar" height="64" width="64" src="<%= current_user.avatar.url %>"></div>
      <div class="main">
        <div class="headline">
    <span class="name"> <%= current_user.name %>
    </span>
</div>

      <div class="comment_content">
        <form accept-charset="UTF-8" action="/comments" class="new_comment" data-remote="true" id="new_comment" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"><input name="authenticity_token" type="hidden" value="NIIMdku7mPA6k9U/ko6W3rMIJfqRJQuEpbkQKmagqf0="></div>
          
          <div>
            <input id="comment_episode_id" name="course_id" type="hidden" value="<%=course_id %>"%>
          </div>
          <div class="formatting">
            支持markdown格式 <a href="javascript:void(0)" class="markdown_link">参考例子</a>
            <div class="markdown_examples" id="markdown_examples" style="display: none">
              <table>
                <tbody><tr>
                  <td><pre>[Link](http://example.com/)</pre></td>
                  <td><a href="http://example.com/">Link</a></td>
                </tr>
                <tr>
                  <td><pre>*Italic*</pre></td>
                  <td><em>Italic</em></td>
                </tr>
                <tr>
                  <td><pre>**Bold**</pre></td>
                  <td><strong>Bold</strong></td>
                </tr>
                <tr>
                  <td><pre>* Listed
* Items
                  </pre></td>
                  <td><ul><li>Listed</li><li>Items</li></ul></td>
                </tr>
                <tr>
                  <td><pre>&gt; Block quote</pre></td>
                  <td><blockquote><p>Block quote</p></blockquote></td>
                </tr>
                <tr>
                  <td><pre>`Inline code`</pre></td>
                  <td><code>Inline code</code></td>
                </tr>
                <tr>
                  <td>
                    <pre>``` ruby
puts "code block"
```
                    </pre>
                  </td>
                  <td>      <div class="code_block">
        <div class="code_header">
          ruby
        </div>
        <div class="CodeRay">
  <div class="code"><pre>puts <span class="s"><span class="dl">"</span><span class="k">code block</span><span class="dl">"</span></span></pre></div>
</div>

      </div>

</td>
                </tr>
              </tbody></table>
            </div>
          </div>
          <div class="field">
            <textarea cols="65" id="comment_content" name="comment[content]" rows="12" style="width: 570px;"></textarea>
          </div>
    <div class="clear"></div>
          <div class="actions">
            <input name="commit" type="submit" class="btn btn-success" value="发表评论">
          </div>
    <div class="clear"></div>
</form>      </div>
    </div>
    <div class="clear"></div>
</div>
<% else %>
  <div class="login-inform">
    <h1><a href="<%=new_session_path %>">登陆</a>参加讨论</h1>
  </div>  
<%end%>

app/views/comments/_index.html.haml
-if comments.size > 0
  -comments.each do |comment|
    .comment
      .avatar
        = image_tag "#{comment.user.avatar.url}", :size => "64x64"
      .main
        .headline
          .name #{comment.user.name}
          .reply
            =image_tag("/assets/reply_button.png", :class => "mention_button", data: { mention: "@#{ comment.user.name }" }) 
        -if comment.user.is_admin?
          .comment_content.content-role(style="background: #fffce9;") #{markdown(comment.content)}
        -else
          .comment_content.content-role #{markdown(comment.content)}
        .clear
-else
  .no-comment
    %h1 快来抢沙发呀~

app/views/comments/add_comment.js.erb
if($(".no-comment"))
  $(".no-comment").remove();
$("#comment_content").val("");
$('.course-item').append("<%= j render partial: 'comment', locals: {comment: @comment} %>");

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.js.erb
$(".course-item").empty();
$("#comments-item").addClass("active");
$('.course-item').empty().append("<%= j render partial: 'index', locals: {comments: @comments} %>")
$('#comments_form').empty().append("<%= j render partial: 'form', locals: {comment: @comment, course_id: @course_id} %>")

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Course:
  = @comment.course_id
%p
  %b User:
  = @comment.user_id
%p
  %b Content:
  = @comment.content

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path