config/routes.rb
#encoding: utf-8
Weber::Application.routes.draw do

  get "session/create"
  
  get "/intro" => "home#index", :as => "intro"

  resources :submits, :feedbacks, :assignments, :comments, :courses
  
  resources :notifications do
    delete :clear, :on => :collection
    get :read, :on => :member
  end

  # 管理员
  namespace :admin do
    resources :courses do
	    get "/download_courseware" => "courses#download_courseware", :as => :download
      # admin course-poster  
      post 'update_poster' => 'courses#update_poster', :as => :update_poster
      # admin course-courseware
      match 'edit_courseware' => 'courses#edit_courseware'
    end
  end

  #邮箱激活
  get '/users(:cad_id,:activate_code)' => 'users#activate_account'
  # 成功页面
  match 'success' => "users#success", :as => :success
  match 'failure' => "users#failure", :as => :failure
	# 编辑edit操作路由
	match '/sign_in' => "sessions#new", :via => :get, :as => :new_session
  match "logout" => "sessions#logout", :as => "logout"
  match '/sign_up' => "users#new", :as => :new_user
	get ':member_name/edit' => 'users#edit', :as => :user_edit
	post '/:member_name/show' => "users#update"
	get '/:member_name' => 'users#show', :as => :user_show
  match '/sessions_path' => "sessions#create", :as => "sessions", :via => :post
  
  get "/:member_name" => "home#show", :as => "member"
  post "/member" => "users#create"

	match "/update_avatar/:member_name" => "users#update_avatar",:as => :update_avatar 
  

  # 课程异步加载
  get "/courses/:course_id/comments" => "comments#index", :as => "comments"
  #get "assignments" => "courses#show", :as => "assignment"

  root :to => 'home#show'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :admin, :email, :id, :name, :password_digest, :password_reset_sent_at, :password_reset_token, :token, :password, :cad_id, :avatar

  # 所有用户
  has_many :comments,   :dependent => :destroy
  has_many :notifications, :dependent => :destroy
  # 普通用户
  has_many :submits,    :dependent => :destroy
  # 管理员
  has_many :courses,    :dependent => :destroy
  has_many :feedbacks,  :dependent => :destroy

  validates_presence_of :name, :email, :on => :create
	# 只有create时才验证密码
	validates_presence_of :password, :on => :create
  validates :name, :email, uniqueness: true

  before_create { generate_token(:token) }
	mount_uploader :avatar, AvatarUploader

  
  def password
    @password
  end
  
  def password=(pass)
    return unless pass
    @password = pass
    generate_password(pass)
  end

  def self.authenticate(params)
    user = User.new(params[:name])
    if user && Digest::SHA256.hexdigest(password) == user.hashed_password
      return user
    end
    false
  end

  def self.authentication(email, password)
    user = User.find_by_email(email)
    if user && Digest::SHA256.hexdigest(password + user.salt) == user.password_digest
      return user
    end
    false
  end
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])  
  end
  
  def is_admin?
    return admin == 1
  end

  def notifications
    Notification.user_notifications(id)
  end
  
  # 数据表中存在的notifications数量，不管read还是unread
  def total_notifications
    Notification.total_notifications(id)
  end

  private
  def generate_password(pass)
    salt = Array.new(10){rand(1024).to_s(36)}.join
    self.salt, self.password_digest = 
      salt, Digest::SHA256.hexdigest(pass + salt)
  end

end

app/controllers/users_controller.rb
# encoding:utf-8
class UsersController < ApplicationController
  require 'debugger'
  layout 'intro', only: [:new]
  before_filter :auth, only: [:new]

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find_by_name(params[:member_name])
    
    render :layout => 'back'
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def edit
   
		@user = User.find_by_name(params['member_name'])
		render :layout => 'back'
	end

  def create
    @user = User.new(params[:user])
    @user.active_code = rand(Time.now.to_i).to_s
    @user.is_activated = false

    respond_to do |format|
      if @user.save
        cookies.permanent[:token] = @user.token
        ActivateMail.sent(@user).deliver 
        format.html { redirect_to user_show_path(@user.name) }
      else
        format.html { render action: "new" }
      end
    end
  end

	# 映射到edit页面
  def update
    @user = User.find(current_user.id)
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to user_show_path(@user.name),
											notice: "更改成功！下次登录请用此信息！" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  def update_avatar
    @user = User.find_by_name(params['member_name'])
	  respond_to do |format|
      format.js do
			  @user.update_attributes(params[:user])
	    end
		end
	end
  def activate_account
    @user = User.find_by_cad_id(params[:cad_id])
    if @user && @user.active_code == params[:active_code]
      @user.is_activated = 1 
      @user.save
      redirect_to :success
    else
      redirect_to :failure
    end
  end
  def failure 
    render :layout => 'intro'
  end

  def success
    render :layout => 'intro'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
%legend 
  %strong 报名信息
= form_for(@user, url: '/member') do |f|
  -if @user.errors.any?
    .error_messages
      %h4 填写信息有误

  .component
    = f.label :name, "姓名"
    = f.text_field :name, :autofocus => true, :style => "width: 280px"
  .component
    = f.label :cad_id, "学号"
    = f.text_field :cad_id, :autofocus => true, :style => "width: 280px"
  .component
    = f.label :email, "Email"
    = f.email_field :email, :autofocus => true, :style => "width: 280px"
  .component
    = f.label :password, "密码"
    = f.password_field :password, :autofocus => true, :style => "width: 280px"
  = f.submit "提交"
 

app/views/users/edit.html.haml
-content_for :body do
  %section#about.wrap.about.role.clearfix
    .content
      .courses.courses-role
        .full
          .course
            .screenshot1#role-screenshot1
              .edit-course-poster(style="margin-bottom:5px;")
                %p 头像
                .poster-preview
                  =image_tag("#{@user.avatar}", :id => "poster")
                .edit-course-poster.btn.btn-info
                  %span#poster-upload-tip 更改头像
                  <input id="poster-fileupload" name="user[avatar]" type="file">
            .course-main(style="height: 490px;")
              .row.span6.form-horizontal(style="margin-top: 100px; margin-left: -70px;")
                = form_for(@user,url: "/#{@user.name}/show",method: 'post') do |f|
                  .control-group
                    = f.label :name,"姓名", class: "control-label"
                    %div.controls
                      = f.text_field :name, :autofocus => true,placeholder: "姓名"
                  .control-group
                    = f.label :email, "邮箱",class: "control-label"
                    %div.controls
                      = f.email_field :email, :autofocus => true, placeholder: "邮箱"
                  .control-group
                    = f.label :cad_id,"学号",class: "control-label"
                    %div.controls
                      = f.text_field :cad_id, :autofocus => true,placeholder: "学号 "
                  .control-group
                    %div.offset3
                      =f.submit "保存更改", class: "btn btn-success"		
-content_for :bootstrap do
  =stylesheet_link_tag 'bootstrap_and_overrides'
-content_for :template_js do
  :javascript
    $(document).ready(function() {
       jQuery(function($) {
           var _tip = $("#poster-upload-tip");
          $('#poster-fileupload').fileupload({
              dataType: 'script',
              url: "/update_avatar/#{@user.name}",
              add: function(e, data){
                types = /(\.|\/)(gif|jpe?g|png)$/i;
                file = data.files[0];
                console.log(file.type);
                console.log(types);
                if (types.test(file.type) || types.test(file.name))
                {
                  data.submit();
                }
                else
                {
                  alert(file.name + " 不是图片，请重新选择！");
                }
              },
              start: function(e) {
                _tip.html('上传中&nbsp;&middot;&middot;&middot;');
              },
              done: function (e, data) {
                _tip.html("头像修改成功!");
              },
          });
        });
      });

app/views/users/failure.html.haml
-content_for :body do
  %nav.global-nav.affix-top
    %h2 PureWeber欢迎您!
  %section#about.wrap.about.role

    %aside.form
      %header
        %h2 注册失败, 请重新验证!

- content_for :bootstrap do
  = stylesheet_link_tag 'bootstrap_and_overrides.css'
%header

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Id
    %th Email
    %th Password digest
    %th Token
    %th Admin
    %th Name
    %th Password reset token
    %th Password reset sent at
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.id
      %td= user.email
      %td= user.password_digest
      %td= user.token
      %td= user.admin
      %td= user.name
      %td= user.password_reset_token
      %td= user.password_reset_sent_at
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
-content_for :body do
  %nav.global-nav.affix-top
    %h2 PureWeber欢迎您!
  %section.wrap#notice
    %p 为了方便我们管理，请填写真实信息，密码将用来登录课程网站。
  %section#about.wrap.about.role

    %aside.form
      = render 'form'
  :javascript
    $(document).ready(function() {
      setTimeout(function () {
        document.getElementById("notice")[0].style("display: none;")
      }, 4000);
    });

- content_for :bootstrap do
  = stylesheet_link_tag 'bootstrap_and_overrides.css'

app/views/users/show.html.haml
-content_for :body do
  %section#about.wrap.about.role.clearfix
    .content
      .course.courses-role
        .full
          .course
            .screenshot1#role-screenshot1
              .edit-course-poster(style="margin-bottom:5px;")
                %p 头像
                .poster-preview
                  = image_tag("#{@user.avatar_url}", :id => "poster")
            .course-main(style="height: 490px;")
              .row.span6(style="margin-top:100px;")
                %ul
                  %li 姓名：#{@user.name} 
                  %br
                  %li 邮箱：#{@user.email}
                  %br
                  %li 学号：#{@user.cad_id}
                .control-group
                  =link_to "编辑",  user_edit_path, :class => "btn btn-success"
-content_for :bootstrap do
  = stylesheet_link_tag 'bootstrap_and_overrides'

app/views/users/success.html.haml
-content_for :body do
  %nav.global-nav.affix-top
    %h2 PureWeber欢迎您!
  %section#about.wrap.about.role

    %aside.form
      %header
        %h2 成功注册! 后台功能开发中。我们会将相关的课程通知发送您的邮箱，请留意查收!

- content_for :bootstrap do
  = stylesheet_link_tag 'bootstrap_and_overrides.css'

app/views/users/update_avatar.js.erb
$('img#poster').replaceWith('<%= image_tag @user.avatar_url,:alt => "Avatar Image",:id => "poster"%>');