config/routes.rb
#encoding: utf-8
Weber::Application.routes.draw do

  get "session/create"
  
  get "/intro" => "home#index", :as => "intro"

  resources :submits, :feedbacks, :assignments, :comments, :courses
  
  resources :notifications do
    delete :clear, :on => :collection
    get :read, :on => :member
  end

  # 管理员
  namespace :admin do
    resources :courses do
	    get "/download_courseware" => "courses#download_courseware", :as => :download
      # admin course-poster  
      post 'update_poster' => 'courses#update_poster', :as => :update_poster
      # admin course-courseware
      match 'edit_courseware' => 'courses#edit_courseware'
    end
  end

  #邮箱激活
  get '/users(:cad_id,:activate_code)' => 'users#activate_account'
  # 成功页面
  match 'success' => "users#success", :as => :success
  match 'failure' => "users#failure", :as => :failure
	# 编辑edit操作路由
	match '/sign_in' => "sessions#new", :via => :get, :as => :new_session
  match "logout" => "sessions#logout", :as => "logout"
  match '/sign_up' => "users#new", :as => :new_user
	get ':member_name/edit' => 'users#edit', :as => :user_edit
	post '/:member_name/show' => "users#update"
	get '/:member_name' => 'users#show', :as => :user_show
  match '/sessions_path' => "sessions#create", :as => "sessions", :via => :post
  
  get "/:member_name" => "home#show", :as => "member"
  post "/member" => "users#create"

	match "/update_avatar/:member_name" => "users#update_avatar",:as => :update_avatar 
  

  # 课程异步加载
  get "/courses/:course_id/comments" => "comments#index", :as => "comments"
  #get "assignments" => "courses#show", :as => "assignment"

  root :to => 'home#show'
end

app/models/submit.rb
class Submit < ActiveRecord::Base
  attr_accessible :course_id, :position, :user_id
  
  validates :position, :course_id, :user_id, :presence => true 

  belongs_to :course
  belongs_to :user
  
end

app/controllers/submits_controller.rb
class SubmitsController < ApplicationController
  # GET /submits
  # GET /submits.json
  def index
    @submits = Submit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @submits }
    end
  end

  # GET /submits/1
  # GET /submits/1.json
  def show
    @submit = Submit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @submit }
    end
  end

  # GET /submits/new
  # GET /submits/new.json
  def new
    @submit = Submit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @submit }
    end
  end

  # GET /submits/1/edit
  def edit
    @submit = Submit.find(params[:id])
  end

  # POST /submits
  # POST /submits.json
  def create
    @submit = Submit.new(params[:submit])

    respond_to do |format|
      if @submit.save
        format.html { redirect_to @submit, notice: 'Submit was successfully created.' }
        format.json { render json: @submit, status: :created, location: @submit }
      else
        format.html { render action: "new" }
        format.json { render json: @submit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /submits/1
  # PUT /submits/1.json
  def update
    @submit = Submit.find(params[:id])

    respond_to do |format|
      if @submit.update_attributes(params[:submit])
        format.html { redirect_to @submit, notice: 'Submit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @submit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submits/1
  # DELETE /submits/1.json
  def destroy
    @submit = Submit.find(params[:id])
    @submit.destroy

    respond_to do |format|
      format.html { redirect_to submits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/submits_helper.rb
module SubmitsHelper
end

app/views/submits/_form.html.haml
= form_for @submit do |f|
  - if @submit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@submit.errors.count, "error")} prohibited this submit from being saved:"
      %ul
        - @submit.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :course_id
    = f.number_field :course_id
  .field
    = f.label :position
    = f.text_field :position
  .actions
    = f.submit 'Save'

app/views/submits/edit.html.haml
%h1 Editing submit

= render 'form'

= link_to 'Show', @submit
\|
= link_to 'Back', submits_path

app/views/submits/index.html.haml
%h1 Listing submits

%table
  %tr
    %th User
    %th Course
    %th Position
    %th
    %th
    %th

  - @submits.each do |submit|
    %tr
      %td= submit.user_id
      %td= submit.course_id
      %td= submit.position
      %td= link_to 'Show', submit
      %td= link_to 'Edit', edit_submit_path(submit)
      %td= link_to 'Destroy', submit, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Submit', new_submit_path

app/views/submits/new.html.haml
%h1 New submit

= render 'form'

= link_to 'Back', submits_path

app/views/submits/show.html.haml
%p#notice= notice

%p
  %b User:
  = @submit.user_id
%p
  %b Course:
  = @submit.course_id
%p
  %b Position:
  = @submit.position

= link_to 'Edit', edit_submit_path(@submit)
\|
= link_to 'Back', submits_path