config/routes.rb
#encoding: utf-8
Weber::Application.routes.draw do

  get "session/create"
  
  get "/intro" => "home#index", :as => "intro"

  resources :submits, :feedbacks, :assignments, :comments, :courses
  
  resources :notifications do
    delete :clear, :on => :collection
    get :read, :on => :member
  end

  # 管理员
  namespace :admin do
    resources :courses do
	    get "/download_courseware" => "courses#download_courseware", :as => :download
      # admin course-poster  
      post 'update_poster' => 'courses#update_poster', :as => :update_poster
      # admin course-courseware
      match 'edit_courseware' => 'courses#edit_courseware'
    end
  end

  #邮箱激活
  get '/users(:cad_id,:activate_code)' => 'users#activate_account'
  # 成功页面
  match 'success' => "users#success", :as => :success
  match 'failure' => "users#failure", :as => :failure
	# 编辑edit操作路由
	match '/sign_in' => "sessions#new", :via => :get, :as => :new_session
  match "logout" => "sessions#logout", :as => "logout"
  match '/sign_up' => "users#new", :as => :new_user
	get ':member_name/edit' => 'users#edit', :as => :user_edit
	post '/:member_name/show' => "users#update"
	get '/:member_name' => 'users#show', :as => :user_show
  match '/sessions_path' => "sessions#create", :as => "sessions", :via => :post
  
  get "/:member_name" => "home#show", :as => "member"
  post "/member" => "users#create"

	match "/update_avatar/:member_name" => "users#update_avatar",:as => :update_avatar 
  

  # 课程异步加载
  get "/courses/:course_id/comments" => "comments#index", :as => "comments"
  #get "assignments" => "courses#show", :as => "assignment"

  root :to => 'home#show'
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :user_id, :content, :mark, :submit_id

  validates :content, :mark, :presence => true
  belongs_to :submit
  belongs_to :user
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedbacks }
    end
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/new
  # GET /feedbacks/new.json
  def new
    @feedback = Feedback.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/1/edit
  def edit
    @feedback = Feedback.find(params[:id])
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(params[:feedback])

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render json: @feedback, status: :created, location: @feedback }
      else
        format.html { render action: "new" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feedbacks/1
  # PUT /feedbacks/1.json
  def update
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to feedbacks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.haml
= form_for @feedback do |f|
  - if @feedback.errors.any?
    #error_explanation
      %h2= "#{pluralize(@feedback.errors.count, "error")} prohibited this feedback from being saved:"
      %ul
        - @feedback.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :assignment_id
    = f.number_field :assignment_id
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :mark
    = f.number_field :mark
  .actions
    = f.submit 'Save'

app/views/feedbacks/edit.html.haml
%h1 Editing feedback

= render 'form'

= link_to 'Show', @feedback
\|
= link_to 'Back', feedbacks_path

app/views/feedbacks/index.html.haml
%h1 Listing feedbacks

%table
  %tr
    %th Assignment
    %th Content
    %th Mark
    %th
    %th
    %th

  - @feedbacks.each do |feedback|
    %tr
      %td= feedback.assignment_id
      %td= feedback.content
      %td= feedback.mark
      %td= link_to 'Show', feedback
      %td= link_to 'Edit', edit_feedback_path(feedback)
      %td= link_to 'Destroy', feedback, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Feedback', new_feedback_path

app/views/feedbacks/new.html.haml
%h1 New feedback

= render 'form'

= link_to 'Back', feedbacks_path

app/views/feedbacks/show.html.haml
%p#notice= notice

%p
  %b Assignment:
  = @feedback.assignment_id
%p
  %b Content:
  = @feedback.content
%p
  %b Mark:
  = @feedback.mark

= link_to 'Edit', edit_feedback_path(@feedback)
\|
= link_to 'Back', feedbacks_path